version: '3.8'

services:
  app:
    build: .
    command: poetry run python main.py
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "127.0.0.1:8001:8001"
    environment:
      - BASE_URL=127.0.0.1:8000
      - USE_WSGI=0
      