apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diploma-sso
  template:
    metadata:
      labels:
        app: diploma-sso
    spec:
      containers:
      - name: diploma-sso
        image: diploma_sso:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+asyncpg://postgres:password@diploma-sso-db/postgres"
        - name: SECRET_KEY
          value: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
        - name: ADMIN_USERNAME
          value: "admin@admin.ru"
        - name: ADMIN_PASSWORD
          value: "admin"
        - name: EMAIL_LOGIN
          value: "parking_test01@sibnet.ru"
        - name: EMAIL_PASSWORD
          value: "parking_test01"
        - name: USE_WSGI
          value: "0"
        - name: CONFIG
          value: "config.json"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: diploma-sso-service
spec:
  selector:
    app: diploma-sso
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
